apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fetch-server-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: fetch-server-cronjob
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - name: "fetch-server"
            image: "gcr.io/awesome-238003/awesome-fetch-server:v2019.05.15"
            envFrom:
            - secretRef:
                name: fetch-server-env
            env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "200m"
                memory: "512Mi"
          restartPolicy: OnFailure