apiVersion: "v1"
kind: "Service"
metadata:
  name: "awesome-nginx"
  labels:
    app: "awesome-nginx"
spec:
  ports:
  - port: 80
    name: https
  selector:
    app: "awesome-nginx"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesome-nginx
  labels:
    app: awesome-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "awesome-nginx"
  template:
    metadata:
      labels:
        app: "awesome-nginx"
    spec:
      volumes:
      - name: awesome-api-nginx-conf
        configMap:
          name: awesome-api-nginx-conf
      containers:
      - name: nginx
        image: nginx:1.15.12-alpine
        volumeMounts:
        - name: awesome-api-nginx-conf
          mountPath: /etc/nginx/conf.d/
        ports:
        - containerPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: awesome-api-lb.anhminhltd.com
spec:
  hosts:
  - "awesome-api-lb.anhminhltd.com"
  gateways:
  - awesome-gateway
  http:
  - route:
    - destination:
        host: awesome-nginx
    retries:
      attempts: 3
      perTryTimeout: 3s